### ISSUE TITLE
Is node->cluster working for view-tree?

### ISSUE THREAD

**Issue by arichiardi** [ztellman/rhizome#16]
Hello Zach!
A genuine question, is clustering working for view-tree? My definition:

```(defn show-tree
    [root]
    (viz/view-tree node-branch? node-children root
                   :options {:dpi 48}
                   :node->descriptor (fn [n] {:label (str n)})
                   :node->cluster :index))```
    
Does not cluster on my :index key...keep up the good work!

**Comment by ztellman** [comment]
No, I'm not propagating the `:node->cluster` or `:cluster->parent` keys from `view-tree` to `view-graph`, which is just an oversight on my part.  I'll fix that right now.

**Comment by arichiardi** [comment]
Great thank you!  I have also noticed that with big graphs (2^19 the smallest that I have available here) is difficult to dump trees, ok ok... it is understandable...but I thought I should report it to you...the memory usage goes up like crazy then stabilizes...I waited almost half an hour but nothing happened...what is the biggest graph you've been able to print?

**Comment by ztellman** [comment]
I haven't tried anything as big as 500k nodes.  Keep in mind that what I need to do is generate a document representing those docs (not very hard), feed that into `dot`, which needs to parse it (probably a little harder), figure out a sane layout for all those nodes (very hard), render that to an image, and then display the image (very memory intensive).  You might try rendering the graph to a dot file using `rhizome.dot`, and then use the command line tool directly where you can experiment with different layout strategies that might be cheaper.

**Comment by ztellman** [comment]
This should be fixed in `0.2.6-SNAPSHOT`.

**Comment by arichiardi** [comment]
It displays now the boxing, but there is no label...am I doing it right?

```(defn show-tree
  [root]
  (viz/view-tree node-branch? node-children root
                 :options {:dpi 48}
                 :node->descriptor (fn [n] {:label (str n)})
                 :node->cluster :index
                 :cluster->descriptor (fn [n] {:label (:index n)})))```

**Comment by ztellman** [comment]
The cluster identifiers are the `:index`, which you're then calling `:index` on again.  Try `:cluster->descriptor (fn [n] {:label n})` and see what happens.

**Comment by arichiardi** [comment]
Like-a-boss! Thanks!
