### ISSUE TITLE
rhizome.viz/graph->svg doesn't work

### ISSUE THREAD

**Issue by whamtet** [ztellman/rhizome#21]
Added pull request

**Comment by theronic** [comment]
Can't figure what to pass to graph->svg either

**Comment by whamtet** [comment]
Ok

**Comment by ztellman** [comment]
Crap, sorry, somehow this fell through my inbox without me noticing.  I've merged the change, and I'll cut a new release.

**Comment by whamtet** [comment]
Thanks!!!
